blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/optmix-ai/optmix/discussions
    about: Ask questions, share ideas, and connect with other users.
